#!/usr/bin/env node

var miniMAL = require('./miniMAL-node.js'),
    env = GLOBAL,
    m = miniMAL(env);

env["require"] = require;
env["read-string"] = function(a) { return JSON.parse(a); };
env["slurp"] = function(a) { return require('fs').readFileSync(a,'utf-8'); };
env["load-file"] = function(a) {
    // Enable shebang usage (ignore shebang line)
    var json = env["slurp"](a).replace(/^#![^\n]*\n/, "", "");
    return m.eval(JSON.parse(json));
};

// Node specific
GLOBAL['*ARGV*'] = process.argv.slice(3);
if (process.argv.length > 2) {
    m.rep('["load-file", ["`", "' + process.argv[2] + '"]]');
} else {
    var rl = require('readline').createInterface(
            process.stdin, process.stdout, false, false);
    function x(l) {
        l && console.log(m.rep(l));
        rl.question("user> ", x);
    }
    x()
}

