#!/usr/bin/env node

var m = require('./miniMAL-node.js')(global);

Object.assign(m, {
    "require": require,
    // Override to enable shebang usage (ignore shebang line)
    "load":    a => m.eval(JSON.parse(m.slurp(a).replace(/^#![^\n]*\n/, ""))),
    "ARGS":    process.argv.slice(3)
})

// Node specific
if (process.argv[2]) {
    m.load(process.argv[2])
} else {
    console.log("miniMAL 1.0.2")
    require("repl").start({
        eval: (...a) => console.log(m.rep(a[0])) | a[3](),
        terminal: false})
}
