#!/usr/bin/env node

let m = require('./miniMAL-node.js')(global)
m.eval(require('./miniMAL-core.js'))

Object.assign(m, {
    "require": require,
    // Override to enable shebang usage (ignore shebang line)
    "load":    a => m.eval(JSON.parse(m.slurp(a).replace(/^#![^\n]*\n/, ""))),
    "ARGS":    process.argv.slice(3)
})

if (process.argv[2]) { return m.load(process.argv[2]) }

console.log("miniMAL 1.1.0")
require("repl").start({eval: (...a) => console.log(m.rep(a[0])) | a[3]()})
