name: Push (compose tests)

on:
  push: {}
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  tests-and-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install JavaScript and ClojureScript node modules
        run: |
            ( cd js && npm install )
            ( cd cljs && npm install )

      - name: JavaScript Step Tests
        run: make test^js

      - name: JavaScript Regression Tests
        run: make REGRESS=1 test^js

      - name: Python Step Tests
        run: make test^python

      - name: Python Regression Tests
        run: make REGRESS=1 test^python

      - name: ClojureScript Step Tests
        run: make test^cljs

      - name: ClojureScript Regression Tests
        run: make REGRESS=1 test^cljs

      - name: Generate stats
        run: |
            make stats # Build compressed artifacts

            echo "### JavaScript stats" >> $GITHUB_STEP_SUMMARY
            echo -e "| Lines | Bytes | File |\n| ----- | ----- | ---- |" >> $GITHUB_STEP_SUMMARY
            make stats^js | awk '/ *[0-9]+/ {print "| "$1" | "$2" | "$3" | "}' >> $GITHUB_STEP_SUMMARY

            echo "### Python stats" >> $GITHUB_STEP_SUMMARY
            echo -e "| Lines | Bytes | File |\n| ----- | ----- | ---- |" >> $GITHUB_STEP_SUMMARY
            make stats^python | awk '/ *[0-9]+/ {print "| "$1" | "$2" | "$3" | "}' >> $GITHUB_STEP_SUMMARY

            echo "### ClojureScript stats" >> $GITHUB_STEP_SUMMARY
            echo -e "| Lines | Bytes | File |\n| ----- | ----- | ---- |" >> $GITHUB_STEP_SUMMARY
            make stats^cljs | awk '/ *[0-9]+/ {print "| "$1" | "$2" | "$3" | "}' >> $GITHUB_STEP_SUMMARY
